Silence loggers using `nil` instead of `false`
`false` is causing errors:

```
Failure/Error:
  create_table(:users, force: true) do |t|
    t.text :data
    t.json :smart_data
  end

NoMethodError:
  undefined method `debug?' for false
```

From my limited investigation, it looks like Rails checks explicity for
`nil` loggers when logging.